puts "🌱 Seeding accommodation..."
a1 = Accommodation.create(name: "Riu Cancun - All Inclusive", location: "Mexico", description: "Catch some rays at the beach or spend the day relaxing at Riu Cancun All Inclusive's full-service spa. Then enjoy a meal at one of the property's 6 restaurants. All 569 rooms feature modern comforts like flat-screen TVs with satellite channels, along with free WiFi. Balconies, minibars, and free bottled water are among the other amenities available to guests.", image: "https://ik.imagekit.io/vonlhgv94ld/hotel-riu-cancun_dZHv76c-s.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644990486700", like: 20 )
a2 = Accommodation.create(name: "Las Ventanas al Paraiso, A Rosewood Resort", location: "Mexico", description: "In the dramatic desert coastline of Los Cabos, where sun, sand and sea converge in Cabo San Lucas, Las Ventanas al Paraíso, a Rosewood Resort consistently redefines pampering and pleasure with incomparable service and attention to detail. The exquisite design of Las Ventanas creates a uniquely beautiful setting for Los Cabos vacations, and the resort’s approach to landscaping is key to its look and feel. ", image: "https://ik.imagekit.io/vonlhgv94ld/cabo__mex?ik-sdk-version=javascript-1.4.3&updatedAt=1644991074243" , like: 50)
a3 = Accommodation.create(name: "Half Moon, Montego Bay" , location: "Jamaica", description: "Half Moon is a luxury oceanfront property with two beautiful beaches outside of Montego Bay. Its 388 air-conditioned rooms are a mix of modern and traditionally-decorated units with living areas, extensive minibars, and flat-screen TVs. Private balconies have ocean, pool, or garden views, and multi-bedroom villas include perks like cooks and butlers. This sprawling resort has tons of amenities including a huge spa, three tasty -- yet pricy -- restaurants, multiple pools, free tennis courts, a kids' club, and a massive gym. At this price point, the hotel has surprising few freebies, and most guests opt for all-inclusive rates as pay-as-you-go prices are sky high.", image: "https://ik.imagekit.io/vonlhgv94ld/002301-01-Infinity_Pool_Sunrise_-_Eclipse_at_Half_Moon-Half_Moon__Jamaica_8ghPzMtuy.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644991314839", like: 45)
a4 = Accommodation.create(name: "Hyatt Zilara Rose Hall" , location: "Jamaica", description: "In this Jamaican paradise on the lush grounds of the historic Rose Hall Great House, all accommodations feature private balconies with spectacular views and unique amenities include swim-up suites and personal butler service. Relax in the oceanfront Zen Spa or indulge in a massage in a private beach cabana. Play a round of golf on the championship White Witch or Cinnamon Hill courses. Enjoy the seclusion of the tranquil pool and three intimate restaurants or explore the adjacent Hyatt Ziva Rose Hall for even more entertainment and dining options, including the best jerk chicken in Jamaica.", image: "https://ik.imagekit.io/vonlhgv94ld/hyatt_jamaica__341b3Q1wWD.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644991473856", like: 60)
a5 = Accommodation.create(name: "Soneva Jani" , location: "Maldives", description: "At Soneva, our unique experiences are in keeping with our interpretation of luxury. Real luxury is about feeling the sand between your toes or enjoying dinner under a canopy of a billion stars. Browse our villas to find your perfect escape, whether you want to relax and unwind with your other half, an action-packed getaway with your friends or a fun-filled, unforgettable stay with your family.", image: "https://ik.imagekit.io/vonlhgv94ld/soneva_maldives_W00m1tni_.png?ik-sdk-version=javascript-1.4.3&updatedAt=1645051525935", like: 100)
a6 = Accommodation.create(name: "Four Seasons Resort Maldives" , location: "Maldives", description: "Gently rising from a sheet of turquoise, at Kuda Huraa it’s hard to tell where ocean ends and sky begins. As captivating beneath the waves as above them, we embrace our stunning surroundings, to bring you closer to the sea and its secrets. Discover the welcoming embrace of a lagoon, flower gardens, a private spa island and spacious new Beach Pavilion hideaways in a charming village setting, awarded a Five-Star rating by Forbes in 2020.", image: "https://ik.imagekit.io/vonlhgv94ld/water-villa-with-pool_k_jx-KXP8.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644991899096", like: 150)
a7 = Accommodation.create(name: "Four Seasons Resort Bora Bora" , location: "Bora Bora", description: "Just-enhanced overwater bungalow suites, beachfront villa estates and underwater adventures welcome you at this sand-fringed idyll in the shadow of Bora Bora’s Mount Otemanu. Toast sunsets from your private plunge pool, marvel at the Tahitian night sky, or simply lose yourself in our lagoon, where the waters teem with exotic reef fish and colourful corals.", image: "https://ik.imagekit.io/vonlhgv94ld/bora_bora_4_seasons_7iEH308km.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644992015734", like: 200)
a8 = Accommodation.create(name: "Jade Mountain Resort" , location: "St. Lucia", description:"Enjoy the exclusivity and privacy of Jade Mountain with all of sister resort Anse Chastanet’s restaurants, bars, boutiques, art gallery, spa, scuba, bike and watersports facilities as well as 2 soft sand beaches available and easily accessible to Jade Mountain guests by foot or resort shuttle at all times.", image: "https://ik.imagekit.io/vonlhgv94ld/Jade_Mountain_Resort_E25DXFlosoT.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644992191903", like: 190)
a9 = Accommodation.create(name: "Ladera Resort Saint Lucia" , location: "St. Lucia", description: "Create unforgettable moments of a lifetime at Ladera Resort St. Lucia, with luxury, romance, adventure, wellness, eco-friendly philosophy and Dasheene’s culinary delights. Uniquely located on a lush volcano ridge 1,000 feet above the Caribbean Sea, each luxurious suite boasts its own private heated plunge pool and an “Open Wall” design, without a fourth wall, allowing for breathtaking panoramas of the Majestic Pitons and deep blue Caribbean Sea.", image: "https://ik.imagekit.io/vonlhgv94ld/Ladera-Resort-Other_BczKskgca.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644992472799", like: 105)
a10 = Accommodation.create(name: "The St. Regis Bora Bora Resort" , location: "Bora Bora", description: "Stay in the largest overwater villas in the South Pacific, starting at 1,550 square feet, and revel in the turquoise blue waters visible from the glass panels. For ultimate privacy, reserve a secluded beach villa surrounded by palms trees. No request will be too small or unattainable for our Butlers, the Signature St. Regis service available 24-hours a day. Sail around the island’s azure waters, or dive under to meet black tip reef sharks and rays up close. After your island adventure, swim in our Lagoonarium, workout in the fitness center, or unwind with a spa treatment. Order a cocktail at the swim-up bar, or sample international and Polynesian-inspired cuisine at our four restaurants. Our resort offers an awe-inspiring backdrop for destination weddings, honeymoons and company retreats.", image: "https://ik.imagekit.io/vonlhgv94ld/bobxr-otemanu-villa-5657-hor-clsc_qwIkHaTA-xr.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1644992647721", like: 250)

puts "Creating Reviews"
r1 = Review.create(comment: "Love this place!", accommodation_id: a1.id)
r2 = Review.create(comment: "Beautiful and affordable.", accommodation_id: a2.id)
r3 = Review.create(comment: "Would totally go back!", accommodation_id: a3.id)
r4 = Review.create(comment: "Staff was great and the room was very clean!", accommodation_id: a4.id)
r5 = Review.create(comment: "A bit expensive but totally worth it for an anniversary or honeymoon trip!", accommodation_id: a5.id)
r6 = Review.create(comment: "Love this place!", accommodation_id: a6.id)
r7 = Review.create(comment: "Amazing views!", accommodation_id: a7.id)
r8 = Review.create(comment: "I would definitely reccommend this resort!", accommodation_id: a8.id)
r9 = Review.create(comment: "My husband and I had an amazing time. Staff was super friendly and the food was great!", accommodation_id: a9.id)
r10 = Review.create(comment: "Love this place!", accommodation_id: a10.id)


# Seed your database here

puts "✅ Done seeding!"
